[package]
name = "n64-si"
description = "The Serial Interface for the N64, also known as SI"
version = "0.1.0"
edition = "2021"

[dependencies]
n64-pif = { path = "../n64-pif" }
n64-common = { path = "../n64-common" }
