[package]
name = "delusion64"
version = "0.1.0"
edition = "2021"

[features]
default = ["debug-print"]
debug-print = []

[dependencies]
clap = { version = "4.3.0", features = ["derive"] }
mips-lifter = { path = "../mips-lifter", default-features = false }
n64-cartridge = { path = "../n64-cartridge" }
