[package]
name = "emgui"
description = "A GUI library designed for emulators, using egui."
version = "0.1.0"
edition = "2021"

[dependencies.eframe]
version = "0.23.0"
default-features = false
features = ["default_fonts", "wgpu", "wayland", "x11"]
